const List<String> kProyekBulkImport = [
  'Updating Direktori Usaha/Perusahaan Ekonomi Lanjutan (Groundcheck SBR)',
  'Pengolahan Peta Wilkerstat 2026',
  'Master File Desa',
  'Data Tunggal Sosial dan Ekonomi Nasional (DTSEN)',
  'Pemutakhiran Data Perkembangan Desa (PODES) 2026',
  'Berbagi Ilmu',
  'Bappenas',
  'Laporan Pemotongan Ternak Bulanan (LPTB)',
  'Pengisian LKE ZI (WBK/WBBM)',
  'Jumat Sehat',
  'Revisi Anggaran',
  'Pendataan Laporan Triwulanan PP/TPI',
  'Program Manajemen Perubahan dan Implementasi RB',
  'Laporan Tahunan Perusahan Budidaya Perikanan (LTB)',
  'Form Rencana Aksi (FRA) Triwulanan',
  'Matriks Peran Hasil (MPH)',
  'Perjanjian Kinerja (PK)',
  'Sakernas Tahun 2026',
  'Rencana Strategis (Renstra)',
  'Rencana Penarikan Dana (RPD)',
  'Back Office System (BOS)',
  'Kompetensi pegawai',
  'Melaksanakan pelayanan Rekomendasi kegiatan Statistik (Romantik) seseuai standar',
  'Survei Harga Kemahalan Konstruksi (SHKK)',
  'Sasaran Kinerja Pegawai/KipApp',
  'Publikasi Kecamatan Dalam Angka',
  'Survei captive power',
  'Publikasi Kabupaten Minahasa Selatan Dalam Angka',
  'Disiplin Pegawai',
  'Survei IBS Tahunan (STPIM)',
  'Survei Harga Konsumen (SHK)',
  'Terlaksananya Survei Harga Perdesaan',
  'Pemutakhiran website',
  'Evaluasi Penyelenggaraan Statistik Sektoral (EPSS)',
  'Survei Kebutuhan Data (SKD)',
  'Sensus Ekonomi 2026',
  'Pembinaan Statistik Sektoral (PSS)',
  'Survei Harga Produsen (SHP, SHPJ, SHPT)',
  'Pemanfaatan Perangkat dan Jaringan TI',
  'Melaksanakan pelayanan metadata statistik sektoral sesuai standar',
  'Konten media sosial yang kreatif dan inovatif',
  'Pemeliharaan Jaringan dan Perangkat TI',
  'Survei Sosial Ekonomi Nasional (SUSENAS) 2026',
  'Desa Cinta Statistik (DESA CANTIK) 2026',
  'Cuti Pegawai',
  'Reward dan Punishment pegawai',
  'Karpeg/Karis/Karsu/Taspen/Tapera',
  'Pemilihan Insan Statistik Teladan',
  'Kesejahteraan Pegawai (Tunjangan Kinerja pegawai, Uang Makan pegawai, Uang Lembur pegawai)',
  'Pemutakhiran data pegawai pada Simpeg dan SIASN',
  'Survei Budaya Organisasi',
  'Pengelolaan LHKPN/SPT',
  'Penyusunan Laporan Kinerja',
  'Survei Harga Perdesaan (HKD dan HD)',
  'Survei Tanaman Pangan/Ubinan',
  'Survei Harga Perdagangan Besar (SHPB)',
  'Survei Kerangka Sampel Area (KSA)',
  'Updating DPP dan DUTL',
  'Survei Perusahaan Perkebunan Bulanan (Sedapp Online)',
  'VN-Hortikultura',
  'Survei Perusahaan Perkebunan (SKB) Tahunan',
  'Statistik Pertanian Tanaman Pangan (SP)',
  'Survei Biaya Hidup (SBH)',
  'Pelayanan Statistik Terpadu',
  'Survei Nasional Literasi dan Inklusi Keuangan (SNLIK)',
];
